# This is a basic workflow to help you get started with Actions

# name of workflow (as will appear in the Github Actions dashboard)
name: ExternalUpdate

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" (this is a name, can be changed, and will appear in the Github Actions dashboard)
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # This makes it possible to work "locally" with the files of your repo
    - uses: actions/checkout@v2

    # Delete old folder (as we will "try" to update it from files from the external repo)
    - name: Delete to-be-replaced folder
      run:
          rm -rf src

    # Clone external repo and copy folder over
    - name: Clone external repo and copy files over
      run: |
          git clone https://github.com/azrafe7/hxOrderedMap cloned_repo
          cp -r cloned_repo/src src

    # Setup git user details (REQUIRED) and git-add the copied files
    - name: Setup git user details and git-add
      run: |
          git config --local user.email "test_gh@github.com"
          git config --local user.name "GitHub Action test"
          git add ./src
          # don't error out if there's nothing to update (https://github.com/ad-m/github-push-action/issues/33)
          git commit -m "Auto publish with data from azrafe7/hxOrderedMap" || echo "Nothing to update"
          git status

    # Push changes to repo (using Github Action by @ad-m)
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #force: true

    # Run git status again (without specifying "name" this time - as it's not mandatory)
    - run:
          git status
